# Generated by Django 4.1.1 on 2023-11-18 22:37

import django.contrib.postgres.indexes
from django.db import migrations, models
from django.contrib.postgres.operations import BtreeGinExtension,TrigramExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
            BtreeGinExtension(),
            TrigramExtension(),
            migrations.RunSQL("CREATE EXTENSION pg_stat_statements;"),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255)),
                ('query', models.TextField()),
                ('page', models.IntegerField()),
                ('date', models.DateField()),
                ('result', models.JSONField()),
            ],
            options={
                'db_table': 'search',
            },
        ),
        migrations.AddIndex(
            model_name='search',
            index=django.contrib.postgres.indexes.GinIndex(fields=['query'], name='query_lower_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='search',
            index=models.Index(fields=['language', 'page'], name='search_languag_fc3bb0_idx'),
        ),
    ]
