# Generated by Django 4.1.1 on 2023-11-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='search',
            name='search_languag_fc3bb0_idx',
        ),
        migrations.AddField(
            model_name='search',
            name='category',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='search',
            index=models.Index(fields=['language', 'page', 'category'], name='search_languag_ef70a0_idx'),
        ),
    ]
