import os
from newsapi import NewsApiClient
import datetime
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.backends.ddl_references import Statement
import re


newsapi = NewsApiClient(api_key=os.getenv('API_KEY'))

def get_top_headlines(query,language,country,category):
    top_headlines = newsapi.get_top_headlines(q=query,
                                          category=category,
                                          language=language,
                                          country=country)
    return top_headlines

# /v2/everything
def get_news(query,language='en',page=1):
    today = datetime.date.today()
    seven_days_before = today - datetime.timedelta(days=7)

    today = today.strftime("%Y-%m-%d")
    seven_days_before = seven_days_before.strftime("%Y-%m-%d")

    all_articles = newsapi.get_everything(q=query,
                                      from_param=seven_days_before,
                                      to=today  ,
                                      language=language,
                                      sort_by='publishedAt',
                                      page=page
                                      )
    return all_articles


    
def add_search_partitions(sql, editor, db_table):
    partitions = []
    for lang in ['en','ar']:
            partitions.append(
                f"create table {db_table}_{lang} partition of {editor.quote_name(db_table)} for values in ('{lang}');")
    partitions = '\n'.join(partitions)
    primary_keys = ",primary key (id ,language))"
    sql = sql.replace("serial NOT NULL PRIMARY KEY", "serial NOT NULL")
    sql = '%s %s PARTITION BY LIST(language);\n%s' % (
        sql.rstrip(');'), primary_keys, partitions)
    return sql


def new_execute(self, sql, params=()):
    model = 'search'
    if type(sql) == str and sql.startswith('CREATE TABLE "{}"'.format(model)):
        sql = sql.replace('bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY',
                        'bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY')
        sql = add_search_partitions(sql, self, model)
    reference_str = ') REFERENCES "{}" ("id")'.format(model)
    if type(sql) == Statement and reference_str in str(sql):
        sql = str(sql).replace(reference_str,
                                ', "language") REFERENCES "{}" ("id", "language")'.format(model))
    if 'SET CONSTRAINT' in str(sql):
        parsed = re.findall('"([a-zA-Z0-9_]*)"', str(sql))
        source_table_name = parsed[0]
        destination_table_name = parsed[3]
        constraint_name = parsed[2]
        column_name = parsed[1]
        sql = 'ALTER TABLE "{}" ADD COLUMN "{}" integer NULL; ALTER TABLE "{}" ADD CONSTRAINT "{}" FOREIGN KEY ("{}", "language") REFERENCES "{}" ("id", "language") DEFERRABLE INITIALLY DEFERRED'.format(
            source_table_name, column_name, source_table_name, constraint_name, column_name, destination_table_name)
    self.old_execute(sql, params)


BaseDatabaseSchemaEditor.old_execute = BaseDatabaseSchemaEditor.execute
BaseDatabaseSchemaEditor.execute = new_execute
