# Generated by Django 4.1.1 on 2023-10-18 10:22

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import main.models.document
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=255, null=True, unique=True)),
                ('mobile', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('passport_no', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('visa_expiry', models.DateField(blank=True, null=True)),
                ('rera_no', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('rera_expiry', models.DateField(blank=True, null=True)),
                ('job_title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('shareholding', models.IntegerField(blank=True, default=0, null=True)),
                ('is_owner_or_partner', models.BooleanField(blank=True, default=False, null=True)),
                ('is_authorised_signatory', models.BooleanField(blank=True, default=False, null=True)),
                ('is_admin', models.BooleanField(blank=True, default=False, null=True)),
                ('is_agent_representative', models.BooleanField(blank=True, default=False, null=True)),
                ('password', models.CharField(blank=True, max_length=250)),
                ('random_password', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('salary', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Company Personnel',
                'verbose_name_plural': 'Company Personnel',
            },
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('country_inc', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('date_inc', models.DateField(blank=True, null=True)),
                ('trade_license', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('trade_license_expiry', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('po_box', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('country_code', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('tax_no', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('orn_no', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('orn_expiry', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField()),
                ('type', models.CharField(choices=[('complete_profile', 'complete_profile'), ('update_profile', 'update_profile')], default='complete_profile', max_length=50)),
                ('can_update_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('agency_information', 'agency_information'), ('bank_details', 'bank_details'), ('legal_documents', 'legal_documents'), ('company_personnel', 'company_personnel'), ('all', 'all')], max_length=50), default=list, size=None)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.agency')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=main.models.document.user_agency_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(blank=True, choices=[('BANK_DETAILS', 'Bank Details'), ('TRADE_LICENSE', 'Trade License'), ('MEMORANDUM', 'Memorandum of Articles of Association'), ('BOARD_RESOLUTION', 'Board Resolution'), ('POWER_OF_ATTORNEY', 'Power of Attorney'), ('TAX_CERTIFICATE', 'Tax Certificate'), ('REAL_ESTATE_CERTIFICATE', 'Real Estate Registration Certificate'), ('PASSPORT', 'Passport'), ('NATIONAL_ID', 'National ID'), ('VISA', 'Visa'), ('RERA', 'RERA / Brokergae Card'), ('OTHER', 'Other')], default='BANK_DETAILS', max_length=255, null=True)),
                ('doc_variety', models.CharField(blank=True, choices=[('LEGAL_DOCUMENT', 'Legal Document'), ('PERSONAL_DOCUMENT', 'personal Document')], default='LEGAL_DOCUMENT', max_length=255, null=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_documents', to='main.agency')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('account_no', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('branch', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('swift_code', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('iban', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='main.agency')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_personnels', to='main.agency'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
